/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package src;
import javax.swing.JOptionPane;
import java.sql.ResultSet;
import java.sql.SQLException;
/**
 *
 * @author saram
 */
public class EliminarMP extends javax.swing.JDialog {

    static ResultSet rs;
    //envia guardar con esto escrito
    String cadena;
    String consulta;
    String i;
    int id;
    /**
     * Creates new form EliminarProd
     */
    public EliminarMP(javax.swing.JDialog parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnmodificarIdP = new javax.swing.JButton();
        txtCantidadMP = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtIdMP = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        btnEliminar = new javax.swing.JButton();
        txtNombreMP = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Eliminar Materia Prima");

        btnmodificarIdP.setText("Buscar clave");
        btnmodificarIdP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmodificarIdPActionPerformed(evt);
            }
        });

        txtCantidadMP.setEditable(false);

        jLabel3.setText("Nombre de materia prima:");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Eliminar materia prima");

        jLabel2.setText("Clave de materia prima:");

        jLabel7.setText("Cantidad existente (gr):");

        btnEliminar.setText("Eliminar Materia Prima");
        btnEliminar.setEnabled(false);
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        txtNombreMP.setEditable(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(jLabel7))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNombreMP, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 267, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtIdMP)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnmodificarIdP, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtCantidadMP))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(114, 114, 114))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtIdMP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnmodificarIdP, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtNombreMP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(txtCantidadMP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addComponent(btnEliminar)
                .addContainerGap(90, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnmodificarIdPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmodificarIdPActionPerformed
        int cont =0;
        if(txtIdMP.getText().length() > 0){
            for(int x=0; x< txtIdMP.getText().length(); x++){
                if(txtIdMP.getText().charAt(x) >= 48 && txtIdMP.getText().charAt(x) <= 57){
                    cont++;
                }
            }
            if(cont == txtIdMP.getText().length()){
                if(txtIdMP.getText().length()== 4){
                    try{
                        consulta = "execute busquedaMP '"+txtIdMP.getText()+"'";
                        rs = Conexion.Consulta(consulta);
                        rs.next();
                        if(rs.getString(2) != null ){
                            txtNombreMP.setText(rs.getString(2));
                            txtCantidadMP.setText(rs.getString(3));
                            txtNombreMP.setEditable(true);
                            txtCantidadMP.setEditable(true);
                            btnEliminar.setEnabled(true);
                            txtIdMP.setEditable(false);
                        }
                        else{
                            JOptionPane.showMessageDialog(this, "No hay datos registrados con esta clave",
                                "Clave no encontrada", JOptionPane.INFORMATION_MESSAGE);
                        }
                    }
                    catch(SQLException ex){
                        System.out.println("No se ha realizado la conexion");
                        System.out.println(ex.getMessage());
                        JOptionPane.showMessageDialog(this, "El clave no se encuntra registrado en la base de datos",
                            "Clave no encontrado", JOptionPane.ERROR_MESSAGE);
                    }
                }
                else{
                    JOptionPane.showMessageDialog(this, "La clave debe estar compuestapor 4 caracteres de 0-9",
                        "Clave incorrecta", JOptionPane.ERROR_MESSAGE);
                }
            }
            else{
                JOptionPane.showMessageDialog(this, "Solo se aceptan numeros enteros de 0-9 ",
                    "Datos no validos", JOptionPane.ERROR_MESSAGE);
            }
        }
        else{
            JOptionPane.showMessageDialog(this, "El campo no ha sido llenado",
                "Datos no llenados", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnmodificarIdPActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        int respuesta = JOptionPane.showConfirmDialog(this,
            "¿Está seguro de eliminarla?", "Confirmando eliminación",
            JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE, null);
        if(respuesta == JOptionPane.YES_OPTION){
            cadena = "execute eliminarMP '" +txtIdMP.getText()+"'";
            Conexion.Enviar(cadena);
            JOptionPane.showMessageDialog(this, "La materia prima ha sido eliminada",
                "Materia prima eliminada", JOptionPane.INFORMATION_MESSAGE);
           this.dispose();
        }
    }//GEN-LAST:event_btnEliminarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnmodificarIdP;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField txtCantidadMP;
    private javax.swing.JTextField txtIdMP;
    private javax.swing.JTextField txtNombreMP;
    // End of variables declaration//GEN-END:variables
}
