/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package src;
import javax.swing.JOptionPane;
import java.sql.ResultSet;
import java.sql.SQLException;
/**
 *
 * @author saram
 */
public class ModificarMP extends javax.swing.JDialog {

    static ResultSet rs;
    //envia guardar con esto escrito
    String cadena;
    String consulta;
    String i;
    int id; 
    /**
     * Creates new form ModificarProd
     */
    public ModificarMP(javax.swing.JDialog parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtNombreMP = new javax.swing.JTextField();
        btnmodificarIdP = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        txtCantidadMP = new javax.swing.JTextField();
        btnGuardar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtIdMP = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Modificar Materia Prima");

        txtNombreMP.setEditable(false);

        btnmodificarIdP.setText("Buscar clave");
        btnmodificarIdP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmodificarIdPActionPerformed(evt);
            }
        });

        jLabel7.setText("Cantidad existente (gr):");

        txtCantidadMP.setEditable(false);

        btnGuardar.setText("Guardar cambios");
        btnGuardar.setEnabled(false);
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Modificar materia prima");

        jLabel2.setText("Clave de materia prima:");

        jLabel3.setText("Nombre de materia prima:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(jLabel7))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNombreMP, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 267, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtIdMP)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnmodificarIdP, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtCantidadMP))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(110, 110, 110))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtIdMP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnmodificarIdP, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtNombreMP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel7)
                    .addComponent(txtCantidadMP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addComponent(btnGuardar)
                .addContainerGap(87, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnmodificarIdPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmodificarIdPActionPerformed
        int cont =0;
        if(txtIdMP.getText().length() > 0){
            for(int x=0; x< txtIdMP.getText().length(); x++){
                if(txtIdMP.getText().charAt(x) >= 48 && txtIdMP.getText().charAt(x) <= 57){
                    cont++;
                }
            }
            if(cont == txtIdMP.getText().length()){
                if(txtIdMP.getText().length()== 4){
                    try{
                        consulta = "execute busquedaMP '"+txtIdMP.getText()+"'";
                        rs = Conexion.Consulta(consulta);
                        rs.next();
                        if(rs.getString(2) != null ){
                            txtNombreMP.setText(rs.getString(2));
                            txtCantidadMP.setText(rs.getString(3));
                            txtNombreMP.setEditable(true);
                            txtCantidadMP.setEditable(true);
                            btnGuardar.setEnabled(true);
                            txtIdMP.setEditable(false);
                        }
                        else{
                            JOptionPane.showMessageDialog(this, "No hay datos registrados con esta clave",
                                "Clave no encontrada", JOptionPane.INFORMATION_MESSAGE);
                        }
                    }
                    catch(SQLException ex){
                        System.out.println("No se ha realizado la conexion");
                        System.out.println(ex.getMessage());
                        JOptionPane.showMessageDialog(this, "No hay datos registrados con esta clave",
                            "Clave no encontrada", JOptionPane.ERROR_MESSAGE);
                    }
                }
                else{
                    JOptionPane.showMessageDialog(this, "La clave debe estar compuestapor 4 caracteres de 0-9",
                        "Clave incorrecta", JOptionPane.ERROR_MESSAGE);
                }
            }
            else{
                JOptionPane.showMessageDialog(this, "Solo se aceptan numeros enteros de 0-9 ",
                    "Datos no validos", JOptionPane.ERROR_MESSAGE);
            }
        }
        else{
            JOptionPane.showMessageDialog(this, "El campo no ha sido llenado",
                "Datos no llenados", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnmodificarIdPActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed

        int cont =0, cont2 = 0;
        String cantidad1 = txtCantidadMP.getText();
        if(txtNombreMP.getText().length() > 0 && txtCantidadMP.getText().length() > 0){
            for(int x=0; x<txtNombreMP.getText().length(); x++){
                if(txtNombreMP.getText().charAt(x) >= 65 && txtNombreMP.getText().charAt(x) <= 90 || txtNombreMP.getText().charAt(x) >= 97 && txtNombreMP.getText().charAt(x) <= 122 || txtNombreMP.getText().charAt(x) == 'Ñ' ||  txtNombreMP.getText().charAt(x) == 'ñ' || txtNombreMP.getText().charAt(x) == 'á' || txtNombreMP.getText().charAt(x) == 'í' || txtNombreMP.getText().charAt(x) == 'ó' || txtNombreMP.getText().charAt(x) == 'ú' || txtNombreMP.getText().charAt(x) == 'é' || txtNombreMP.getText().charAt(x) == 'Á' || txtNombreMP.getText().charAt(x) == 'É' || txtNombreMP.getText().charAt(x) == 'Í' || txtNombreMP.getText().charAt(x) == 'Ó' || txtNombreMP.getText().charAt(x) == 'Ú' || txtNombreMP.getText().charAt(x) == 32 || txtNombreMP.getText().charAt(x) == 46){
                    cont++;
                }
            }
            if(cont == txtNombreMP.getText().length()){
                if(txtNombreMP.getText().length()<= 50){
                    for(int x=0; x<cantidad1.length(); x++){
                        if(cantidad1.charAt(x) >= 48 && cantidad1.charAt(x) <= 57){
                            cont2++;
                        }
                    }
                    if(cont2 == cantidad1.length()){
                        int cantidad = Integer.parseInt(cantidad1);
                        if(cantidad >= 1 && cantidad < 100000){
                            //todo esta bien
                            cadena = "execute modificarMP '"+txtNombreMP.getText()+"', "+txtCantidadMP.getText()+", '"+txtIdMP.getText()+"'";
                            Conexion.Enviar(cadena);
                            JOptionPane.showMessageDialog(this, "La Materia Prima ha sido modificado",
                                "Materia Prima modificada y guardada", JOptionPane.INFORMATION_MESSAGE);
                            this.dispose();
                        }
                        else{
                            JOptionPane.showMessageDialog(this, "Caracteres excedidos, solo de aceptan números 1 - 99999",
                                "Cantidad incorrecta", JOptionPane.ERROR_MESSAGE);
                        }
                    }
                    else{
                        JOptionPane.showMessageDialog(this, "La cantidad solo admite numeros de 0-9 ",
                            "Datos no validos", JOptionPane.ERROR_MESSAGE);
                    }
                }
                else{
                    JOptionPane.showMessageDialog(this, "Solo se aceptan hasta 50 carácteres",
                        "Número de carácteres excedido", JOptionPane.ERROR_MESSAGE);
                }
            }
            else{
                JOptionPane.showMessageDialog(this, "El nombre solo pueder ser compuesto solo por carácteres de A-Z y de a-z puntos, comas y espacios",
                    "Datos no validos", JOptionPane.ERROR_MESSAGE);
            }
        }
        else{
            JOptionPane.showMessageDialog(this, "Revise que todos los campos hayan sido llenados",
                "Datos no llenados", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnGuardarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnmodificarIdP;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField txtCantidadMP;
    private javax.swing.JTextField txtIdMP;
    private javax.swing.JTextField txtNombreMP;
    // End of variables declaration//GEN-END:variables
}
