/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package src;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import static src.AgregarVe.rs;

/**
 *
 * @author eliez
 */
public class ModificarCom extends javax.swing.JDialog {

    static ResultSet rs;
    String consulta;
    String FechaCom;
    String IdProv;
  
   
    //envia guardar con esto escrito
    String cadena;
    //Para validar las claves
    int cont2=0;
    /**
     * Creates new form ModificarCom
     */
    public ModificarCom(javax.swing.JDialog parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnModificarDatos = new javax.swing.JButton();
        txtIdProv = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtIdCom = new javax.swing.JTextField();
        btnBuscarIdPv = new javax.swing.JButton();
        btnBuscarIdV = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        txtFechaV = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        txtNomProv = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Modificar Compras");

        btnModificarDatos.setText("MODIFICAR DATOS");
        btnModificarDatos.setEnabled(false);
        btnModificarDatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarDatosActionPerformed(evt);
            }
        });

        txtIdProv.setBackground(new java.awt.Color(204, 255, 255));
        txtIdProv.setText(" ");
        txtIdProv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdProvActionPerformed(evt);
            }
        });

        jLabel1.setText("CLAVE COMPRA:");

        jLabel10.setText("NOMBRE PROVEEDOR:");

        txtIdCom.setBackground(new java.awt.Color(255, 255, 204));

        btnBuscarIdPv.setText("Buscar");
        btnBuscarIdPv.setEnabled(false);
        btnBuscarIdPv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarIdPvActionPerformed(evt);
            }
        });

        btnBuscarIdV.setText("Buscar");
        btnBuscarIdV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarIdVActionPerformed(evt);
            }
        });

        jLabel3.setText("FECHA COMPRA:");

        txtFechaV.setEditable(false);
        txtFechaV.setBackground(new java.awt.Color(204, 255, 255));

        jButton1.setText("Salir");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel7.setBackground(new java.awt.Color(204, 204, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("MODIFICAR");

        txtNomProv.setEditable(false);
        txtNomProv.setBackground(new java.awt.Color(204, 255, 255));

        jLabel8.setText("CLAVE PROVEEDOR:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtFechaV, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtIdCom, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(30, 30, 30)
                        .addComponent(txtIdProv, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(58, 58, 58)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnBuscarIdPv)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnBuscarIdV)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel10)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtNomProv, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(btnModificarDatos)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(166, 166, 166)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtIdCom, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscarIdV))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtFechaV, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtIdProv, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscarIdPv))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNomProv, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnModificarDatos)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnModificarDatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarDatosActionPerformed
        //valida que se hayan ingresado las claves del trabajador y del cliente
        FechaCom = txtFechaV.getText();
        String claveProv = txtIdProv.getText();
        String IdCom = txtIdCom.getText();

        if (FechaCom.length() == 10){
            //Valida que este en el formato de 00/00/00
            if(Character.isDigit(FechaCom.charAt(0))&& Character.isDigit(FechaCom.charAt(1)) && FechaCom.charAt(2) == '/'
                && Character.isDigit(FechaCom.charAt(3)) && Character.isDigit(FechaCom.charAt(4)) && FechaCom.charAt(5) == '/'
                && Character.isDigit(FechaCom.charAt(6)) && Character.isDigit(FechaCom.charAt(7))
                && Character.isDigit(FechaCom.charAt(8)) && Character.isDigit(FechaCom.charAt(9))){

                //Confirma Modificar
                int res = JOptionPane.showConfirmDialog(this, "¿Esta seguro de Modificar los datos?",
                    "MODIFICAR DATOS",
                    JOptionPane.YES_NO_OPTION,
                    JOptionPane.QUESTION_MESSAGE, null);
                if(res == JOptionPane.YES_OPTION){
                    IdProv = txtIdProv.getText();
                    cadena = "execute modificarCompra '" +claveProv+ "', '" + FechaCom+ "', '" + IdCom +"'";
                    Conexion.Enviar(cadena);
                    this.dispose();
                }
                else{
                    //si no lo agrega borra los datos
                    txtIdProv.setText("");
                    txtIdProv.setEditable(true);

                }

            }
            else{
                JOptionPane.showMessageDialog(this, "La Fecha debe estar en el formato 00/00/0000 con BARRAS",
                    "FORMATO NO VALIDO", JOptionPane.ERROR_MESSAGE);
                txtFechaV.setText("");
            }
        }
        else{
            JOptionPane.showMessageDialog(this, "La Fecha debe estar en el formato 00/00/0000 con BARRAS",
                "FORMATO NO VALIDO", JOptionPane.ERROR_MESSAGE);
            txtFechaV.setText("");
        }
    }//GEN-LAST:event_btnModificarDatosActionPerformed

    private void txtIdProvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdProvActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdProvActionPerformed

    private void btnBuscarIdPvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarIdPvActionPerformed
        // TODO add your handling code here:
        String auxProv = txtIdProv.getText();
        int cont1 = 0;
        for (int x=1; x<auxProv.length(); x++){
            if (Character.isDigit(auxProv.charAt(x))){
                cont1 ++;
            }
        }
        if (auxProv.length() == 4){
            if(auxProv.charAt(0) == 'R' && cont1 == 3){
                try{
                    //busca la clave del cliente
                    cadena="execute consultarPv '"+ txtIdProv.getText()+"'";
                    rs = Conexion.Consulta(cadena);
                    rs.next();
                    if(rs.getString(1).equals(auxProv) && rs.getString(2) != null){
                        txtNomProv.setText(rs.getString(2));
                        txtIdProv.setEditable(false);
                        cont2 ++;
                        btnBuscarIdPv.setEnabled(false);
                        btnModificarDatos.setEnabled(true);
                    }
                    else{
                        JOptionPane.showMessageDialog(this, "La clave no existe", 
                            "Clave no valida", JOptionPane.ERROR_MESSAGE);
                    }
                }
                catch(SQLException e){
                    JOptionPane.showMessageDialog(this, "La clave no existe",
                        "CClave no valida", JOptionPane.ERROR_MESSAGE);
                    txtIdProv.setText("");
                }
            }
            else{
                JOptionPane.showMessageDialog(this, "La clave del proveedor debe ser una cadena que empieza con R mas 3 digitos 0-9",
                    "Clave no valida", JOptionPane.ERROR_MESSAGE);
                txtIdProv.setText("");

            }
        }
        else{
            JOptionPane.showMessageDialog(this, "La clave del proveedor debe ser una cadena que empieza con R mas 3 digitos 0-9",
                "Clave no valida", JOptionPane.ERROR_MESSAGE);
            txtIdProv.setText("");

        }
    }//GEN-LAST:event_btnBuscarIdPvActionPerformed

    private void btnBuscarIdVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarIdVActionPerformed
        String auxCom = txtIdCom.getText();
        int cont=0;
        if (auxCom.length() == 6){
            for(int x = 1;x<6;x++){
                if(auxCom.charAt(x) >= 48 && auxCom.charAt(x) <= 57){
                    cont++;
                }
            }
            //System.out.println(cont);
            if(auxCom.charAt(0) == 'O' && cont == 5){
                try{
                    consulta="execute consultarCompras3 '"+ txtIdCom.getText()+"'";
                    rs = Conexion.Consulta(consulta);
                    rs.next();
                    if(rs.getString(1).equals(auxCom)){
                        btnBuscarIdV.setEnabled(false);
                        txtIdCom.setEditable(false);
                        txtIdProv.setText(rs.getString(3));
                        txtNomProv.setText(rs.getString(2));
                        txtFechaV.setText(rs.getString(4));
                        txtIdProv.setEditable(true);
                        txtFechaV.setEditable(true);
                        btnBuscarIdPv.setEnabled(true);
                    }
                }
                catch(SQLException e){
                    JOptionPane.showMessageDialog(this, "La clave no existe",
                    "Clave invalida", JOptionPane.ERROR_MESSAGE);
                    txtIdCom.setText("");
                    txtIdCom.setText("");
                    btnBuscarIdV.setEnabled(true);
                }
            }
            else{
                JOptionPane.showMessageDialog(this, "La clave de la Compra debe ser una cadena que empieza con O mas 5 digitos 0-9",
                    "Clave no valida", JOptionPane.ERROR_MESSAGE);
                txtIdCom.setText("");
                btnBuscarIdV.setEnabled(true);

            }
        }
        else{
            JOptionPane.showMessageDialog(this, "La clave de la Compra debe ser una cadena que empieza con O mas 5 digitos 0-9",
                "Clave no valida", JOptionPane.ERROR_MESSAGE);
            txtIdCom.setText("");
            btnBuscarIdV.setEnabled(true);

        }
    }//GEN-LAST:event_btnBuscarIdVActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscarIdPv;
    private javax.swing.JButton btnBuscarIdV;
    private javax.swing.JButton btnModificarDatos;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField txtFechaV;
    private javax.swing.JTextField txtIdCom;
    private javax.swing.JTextField txtIdProv;
    private javax.swing.JTextField txtNomProv;
    // End of variables declaration//GEN-END:variables
}
