/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package src;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import java.sql.ResultSet;
import static src.AgregarVe.rs;
/**
 *
 * @author saram
 */
public class ModificarVe extends javax.swing.JDialog {

    static ResultSet res;
    String consulta;
    String FechaV;
    String IdTra;
    String IdC;
    char TipoPago;
    //envia guardar con esto escrito
    String cadena;
    //Para validar las claves
    int cont2=0;
    /**
     * Creates new form ConsultarIdV
     */
    /**
     * Creates new form ModificarVe
     */
    public ModificarVe(javax.swing.JDialog parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel10 = new javax.swing.JLabel();
        txtNomTra1 = new javax.swing.JTextField();
        coTipoPago = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        btnBuscarCl = new javax.swing.JButton();
        txtIdV = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        btnBuscarIdV = new javax.swing.JButton();
        btnModificarDatos = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        txtIdTra = new javax.swing.JTextField();
        txtFechaV = new javax.swing.JTextField();
        txtNomC1 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtIdC = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        btnBuscarTra = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Modificar Ventas");

        jLabel10.setText("NOMBRE DE TRABAJADOR:");

        txtNomTra1.setEditable(false);
        txtNomTra1.setBackground(new java.awt.Color(204, 255, 255));

        coTipoPago.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Contado", "Tarjeta" }));
        coTipoPago.setEnabled(false);
        coTipoPago.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                coTipoPagoActionPerformed(evt);
            }
        });

        jLabel11.setText("NOMBRE DEL CLIENTE:");

        jLabel8.setText("CLAVE DE TRABAJADOR:");

        jLabel1.setText("CLAVE DE VENTA:");

        btnBuscarCl.setText("BUSCAR");
        btnBuscarCl.setEnabled(false);
        btnBuscarCl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarClActionPerformed(evt);
            }
        });

        txtIdV.setBackground(new java.awt.Color(255, 255, 204));

        jLabel9.setText("CLAVE DE CLIENTE:");

        btnBuscarIdV.setText("Buscar");
        btnBuscarIdV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarIdVActionPerformed(evt);
            }
        });

        btnModificarDatos.setText("MODIFICAR DATOS");
        btnModificarDatos.setEnabled(false);
        btnModificarDatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarDatosActionPerformed(evt);
            }
        });

        jLabel3.setText("FECHA: ");

        txtIdTra.setBackground(new java.awt.Color(204, 255, 255));
        txtIdTra.setText(" ");

        txtFechaV.setEditable(false);
        txtFechaV.setBackground(new java.awt.Color(204, 255, 255));

        txtNomC1.setEditable(false);
        txtNomC1.setBackground(new java.awt.Color(204, 255, 255));

        jLabel6.setText("TIPO DE PAGO: ");

        txtIdC.setBackground(new java.awt.Color(204, 255, 255));
        txtIdC.setSelectionColor(new java.awt.Color(204, 255, 255));

        jButton1.setText("Salir");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        btnBuscarTra.setText("BUSCAR");
        btnBuscarTra.setEnabled(false);
        btnBuscarTra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarTraActionPerformed(evt);
            }
        });

        jLabel7.setBackground(new java.awt.Color(204, 204, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("MODIFICAR");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtNomTra1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtIdTra, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnBuscarTra)
                        .addGap(12, 12, 12)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtIdC, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtNomC1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(44, 44, 44)
                .addComponent(btnBuscarCl)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(coTipoPago, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(6, 6, 6)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtFechaV, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtIdV, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnBuscarIdV)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton1))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(343, 343, 343)
                        .addComponent(btnModificarDatos)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtIdV, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscarIdV)
                    .addComponent(jButton1))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtFechaV, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(coTipoPago, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtIdTra, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnBuscarTra)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtIdC, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnBuscarCl)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNomTra1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNomC1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addComponent(btnModificarDatos)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void coTipoPagoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_coTipoPagoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_coTipoPagoActionPerformed

    private void btnBuscarClActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarClActionPerformed
        String auxCli = txtIdC.getText();
        int cont1=0;
        for (int x=1; x<auxCli.length(); x++){
            if (Character.isDigit(auxCli.charAt(x))){
                cont1 ++;
            }
        }
        if (auxCli.length() == 4){
            if(auxCli.charAt(0) == 'C' && cont1 == 3){
                try{
                    //busca la clave del cliente
                    cadena="execute consultarCli '"+ txtIdC.getText()+"'";
                    res = Conexion.Consulta(cadena);
                    res.next();
                    if(res.getString(1).equals(auxCli) && rs.getString(2) != null){
                        txtNomC1.setText(res.getString(2));
                        txtIdC.setEditable(false);
                        //esto es para saber que ya ingreso las 2 claves
                        cont2 ++;
                        btnBuscarCl.setEnabled(false);
                        btnModificarDatos.setEnabled(true);
                    }
                    else{
                        JOptionPane.showMessageDialog(this, "La clave no existe", 
                            "Clave no valida", JOptionPane.ERROR_MESSAGE);
                    }
                }
                catch(SQLException e){
                    JOptionPane.showMessageDialog(this, "La clave no existe",
                        "Clave no valida", JOptionPane.ERROR_MESSAGE);
                    txtIdC.setText("");
                    txtNomC1.setText("");
                }
            }
            else{
                JOptionPane.showMessageDialog(this, "La clave del Clientes debe ser una cadena que empieza con C mas 3 digitos 0-9",
                    "Clave no valida", JOptionPane.ERROR_MESSAGE);
                txtIdC.setText("");
                txtNomC1.setText("");
            }
        }
        else{
            JOptionPane.showMessageDialog(this, "La clave del Clientes debe ser una cadena que empieza con C mas 3 digitos 0-9",
                "Clave no valida", JOptionPane.ERROR_MESSAGE);
            txtIdC.setText("");
            txtNomC1.setText("");
        }
    }//GEN-LAST:event_btnBuscarClActionPerformed

    private void btnBuscarIdVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarIdVActionPerformed
        String auxVe = txtIdV.getText();
        int cont1=0;
        for (int x=0; x<auxVe.length(); x++){
            if (Character.isDigit(auxVe.charAt(x))){
                cont1 ++;
            }
        }
        if (auxVe.length() == 7 && cont1 == 7){
            try{
                //se consulta la clave del producto,  el nombre del producto, el nombre del trabajador, la fecha,el tipo de pago y el total
                //que es lo que no se repite
                consulta="execute consultarVenta3 '"+ txtIdV.getText()+"'";
                res = Conexion.Consulta(consulta);
                res.next();
                if(res.getString(1).equals(auxVe)){
                    btnBuscarIdV.setEnabled(false);
                    txtIdV.setEditable(false);
                    txtIdC.setText(res.getString(2));
                    txtNomC1.setText(res.getString(3));
                    txtIdTra.setText(res.getString(4));
                    txtNomTra1.setText(res.getString(5));
                    txtFechaV.setText(res.getString(6));
                    if(res.getString(7).equals("C")){
                        coTipoPago.setSelectedItem("Contado");
                    }
                    else{
                        coTipoPago.setSelectedItem("Tarjeta");
                    }
                    txtIdC.setEditable(true);
                    txtIdTra.setEditable(true);
                    txtFechaV.setEditable(true);
                    btnBuscarTra.setEnabled(true);
                    coTipoPago.setEnabled(true);

                }
            }
            catch(SQLException e){
                JOptionPane.showMessageDialog(this, "La clave no existe",
                    "Clave no valida", JOptionPane.ERROR_MESSAGE);
                txtIdV.setText("");
                txtIdV.setText("");
                btnBuscarIdV.setEnabled(true);
            }
        }
        else{
            JOptionPane.showMessageDialog(this, "La clave del Clientes debe ser una cadena de 7 digitos 0-9",
                "Clave no valida", JOptionPane.ERROR_MESSAGE);
            txtIdV.setText("");
            btnBuscarIdV.setEnabled(true);

        }
    }//GEN-LAST:event_btnBuscarIdVActionPerformed

    private void btnModificarDatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarDatosActionPerformed
        //valida que se hayan ingresado las claves del trabajador y del cliente
        FechaV = txtFechaV.getText();
        String IdV = txtIdV.getText();
        if(coTipoPago.getSelectedItem().equals("Contado")){
            TipoPago = 'C';

        }
        else{
            TipoPago = 'T';
        }
        if (FechaV.length() == 10){
            //Valida que este en el formato de 00/00/00
            if(Character.isDigit(FechaV.charAt(0))&& Character.isDigit(FechaV.charAt(1)) && FechaV.charAt(2) == '/'
                && Character.isDigit(FechaV.charAt(3)) && Character.isDigit(FechaV.charAt(4)) && FechaV.charAt(5) == '/'
                && Character.isDigit(FechaV.charAt(6)) && Character.isDigit(FechaV.charAt(7))
                && Character.isDigit(FechaV.charAt(8)) && Character.isDigit(FechaV.charAt(9))){
                if(txtIdTra.getText().length() != 0 && txtIdC.getText().length() != 0){
                    //Confirma Modificar
                    int res = JOptionPane.showConfirmDialog(this, "¿Esta seguro de Modificar los datos?",
                        "MODIFICAR DATOS",
                        JOptionPane.YES_NO_OPTION,
                        JOptionPane.QUESTION_MESSAGE, null);
                    if(res == JOptionPane.YES_OPTION){
                        IdTra = txtIdTra.getText();
                        IdC = txtIdC.getText();
                        cadena = "execute modificarVenta '" + IdC + "', '"+ IdTra +"', '" + TipoPago + "', '" + FechaV + "', '" + IdV +"'";
                        Conexion.Enviar(cadena);
                        this.dispose();
                    }
                    else{
                        this.dispose();
                    }
                }
                else{
                    JOptionPane.showMessageDialog(this, "lAS CLAVES NO DEBEN ESTAR EN BLANCO",
                        "FORMATO NO VALIDO", JOptionPane.ERROR_MESSAGE);
                }

            }
            else{
                JOptionPane.showMessageDialog(this, "La Fecha debe estar en el formato 00/00/0000 con BARRAS",
                    "FORMATO NO VALIDO", JOptionPane.ERROR_MESSAGE);
                txtFechaV.setText("");
            }
        }
        else{
            JOptionPane.showMessageDialog(this, "La Fecha debe estar en el formato 00/00/0000 con BARRAS",
                "FORMATO NO VALIDO", JOptionPane.ERROR_MESSAGE);
            txtFechaV.setText("");
        }
    }//GEN-LAST:event_btnModificarDatosActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnBuscarTraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarTraActionPerformed
        String auxTra = txtIdTra.getText();

        if (auxTra.length() == 2){
            if(Character.isDigit(auxTra.charAt(0))&& Character.isDigit(auxTra.charAt(1))){
                try{
                    //obtiene el idTra y lo busca en la tabla
                    consulta="execute consultarTra '"+ auxTra +"'";
                    res = Conexion.Consulta(consulta);
                    res.next();
                    if(res.getString(1).equals(auxTra)&& rs.getString(2) != null){
                        txtNomTra1.setText(res.getString(2));
                        txtIdTra.setEditable(false);
                        //esto es para saber que ya ingreso las 2 claves
                        cont2 ++;
                        btnBuscarTra.setEnabled(false);
                        btnBuscarCl.setEnabled(true);
                    }
                    else{
                        JOptionPane.showMessageDialog(this, "La clave no existe", 
                            "Clave no valida", JOptionPane.ERROR_MESSAGE);
                    }
                }
                catch(SQLException e){
                    JOptionPane.showMessageDialog(this, "La clave no existe",
                        "Clave no valida", JOptionPane.ERROR_MESSAGE);
                    txtIdTra.setText("");
                    txtNomTra1.setText("");
                }
            }
            else{
                JOptionPane.showMessageDialog(this, "La clave del trabajador debe ser una cadena de 2 digitos 0-9",
                    "Clave no valida", JOptionPane.ERROR_MESSAGE);
                txtIdTra.setText("");
                txtNomTra1.setText("");
            }
        }
        else{
            JOptionPane.showMessageDialog(this, "La clave del trabajador debe ser una cadena de 2 digitos 0-9",
                "Clave no valida", JOptionPane.ERROR_MESSAGE);
            txtIdTra.setText("");
            txtNomTra1.setText("");
        }
    }//GEN-LAST:event_btnBuscarTraActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscarCl;
    private javax.swing.JButton btnBuscarIdV;
    private javax.swing.JButton btnBuscarTra;
    private javax.swing.JButton btnModificarDatos;
    private javax.swing.JComboBox<String> coTipoPago;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField txtFechaV;
    private javax.swing.JTextField txtIdC;
    private javax.swing.JTextField txtIdTra;
    private javax.swing.JTextField txtIdV;
    private javax.swing.JTextField txtNomC1;
    private javax.swing.JTextField txtNomTra1;
    // End of variables declaration//GEN-END:variables
}
