/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package src;

/**
 *
 * @author eliez
 */
public class PrincipalCompras extends javax.swing.JDialog {

    /**
     * Creates new form PrincipalCompras
     */
    public PrincipalCompras(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        opcAgregar = new javax.swing.JMenuItem();
        opcConsultar = new javax.swing.JMenuItem();
        opcModificar = new javax.swing.JMenuItem();
        opcSalir = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("COMPRAS");

        jMenu2.setText("ACCIONES");

        opcAgregar.setText("Agregar");
        opcAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opcAgregarActionPerformed(evt);
            }
        });
        jMenu2.add(opcAgregar);

        opcConsultar.setText("Consultar");
        opcConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opcConsultarActionPerformed(evt);
            }
        });
        jMenu2.add(opcConsultar);

        opcModificar.setText("Modificar");
        opcModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opcModificarActionPerformed(evt);
            }
        });
        jMenu2.add(opcModificar);

        opcSalir.setText("Salir");
        opcSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opcSalirActionPerformed(evt);
            }
        });
        jMenu2.add(opcSalir);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 278, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void opcAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcAgregarActionPerformed
        AgregarCom a = new AgregarCom(this, true);
        a.setVisible(true);
    }//GEN-LAST:event_opcAgregarActionPerformed

    private void opcConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcConsultarActionPerformed
        ConsultarCom CIdV = new ConsultarCom(this, true);
        CIdV.setVisible(true);
    }//GEN-LAST:event_opcConsultarActionPerformed

    private void opcModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcModificarActionPerformed
        ModificarCom MV = new ModificarCom(this, true);
        MV.setVisible(true);
    }//GEN-LAST:event_opcModificarActionPerformed

    private void opcSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcSalirActionPerformed
        this.dispose();
    }//GEN-LAST:event_opcSalirActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem opcAgregar;
    private javax.swing.JMenuItem opcConsultar;
    private javax.swing.JMenuItem opcModificar;
    private javax.swing.JMenuItem opcSalir;
    // End of variables declaration//GEN-END:variables
}
